// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2SeBGe67zebuJqLkcdFtyd2YZehSVYY',
    appId: '1:784480873808:web:9457564bda8686d5735055',
    messagingSenderId: '784480873808',
    projectId: 'timescatalogo',
    authDomain: 'timescatalogo.firebaseapp.com',
    storageBucket: 'timescatalogo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSeRTz3NJK6UNnTVCRMlkdS2Xi2wBG9j4',
    appId: '1:784480873808:android:c0288eb521cd0f25735055',
    messagingSenderId: '784480873808',
    projectId: 'timescatalogo',
    storageBucket: 'timescatalogo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAffrjx7vjmkV8DsAGVnOAbwfjSlY1e5QI',
    appId: '1:784480873808:ios:5600ef918b66b00c735055',
    messagingSenderId: '784480873808',
    projectId: 'timescatalogo',
    storageBucket: 'timescatalogo.firebasestorage.app',
    iosBundleId: 'com.example.soccerFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAffrjx7vjmkV8DsAGVnOAbwfjSlY1e5QI',
    appId: '1:784480873808:ios:5600ef918b66b00c735055',
    messagingSenderId: '784480873808',
    projectId: 'timescatalogo',
    storageBucket: 'timescatalogo.firebasestorage.app',
    iosBundleId: 'com.example.soccerFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2SeBGe67zebuJqLkcdFtyd2YZehSVYY',
    appId: '1:784480873808:web:567df89c284eef5a735055',
    messagingSenderId: '784480873808',
    projectId: 'timescatalogo',
    authDomain: 'timescatalogo.firebaseapp.com',
    storageBucket: 'timescatalogo.firebasestorage.app',
  );
}
